<main>
	
	<h1>Ajout d'un auteur</h1>
	<!-- si pas d'attribut action, par défaut, la soumission du formulaire fait un rechargement de la même page-->
	<form class="login" method="post">
		<p>
			<label for='firstname'>Prénom</label>
			<input type="text" name="firstname" id="firstname">
		</p>
		<p>
			<label for='lastname'>Nom</label>
			<input type="text" name="lastname" id="lastname">
		</p>
		
		<button type="submit">Créer l'auteur</button>
	</form>
</main>