<main>
	<h3>Ajouter un article</h3>
    
	<form class="login" method="post" enctype="multipart/form-data"> <!--action="article.phtml-->
	    <p>
		    <label for='category'>Catégorie</label>
			<select name="category" id="category">
			    <option value="">--Please choose an option--</option>
			    <?php foreach($categories as $categorie): ?>
                <option value="<?= $categorie['id_category'] ?>"><?= htmlspecialchars($categorie['category_name']) ?></option>
                <?php endforeach; ?>
            </select>
        </p>
       
		<p>
		    <label for='title'>Titre de l'article</label>
		    <input type="text" name="title" id="title"/>
		</p>
		<p>
		    <label for='texte'>Contenu</label>
		    <textarea name="texte" id="texte"></textarea>
		</p>
		<p>
			<label for="src">Image</label>
			<input type="file" name="src" id="src"/>
		</p>
		<p>	
			<label for="alt">Alt</label>
			<input type="text" name="alt" id="alt"/>
		</p>
		
		 <p>
            <label for='author'>Auteur</label>
            <select name="author" id="author">
			    <option value="">--Please choose an option--</option>
			    <?php foreach($authors as $author): ?>
                <option value="<?= $author['id_author'] ?>"><?= htmlspecialchars($author['first_name']) ?> <?= htmlspecialchars($author['last_name']) ?></option>
                <?php endforeach; ?>
            </select>
        </p>

			<button type="submit">Enregistrer</button>
	</form>
	
</main>