<main>

    <section class="title">
        <h1>Titre de l'événement</h1>
    </section>

    <section class="about">
        <h2>Something...</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae similique nisi asperiores libero accusamus voluptates rem aperiam iusto dolor. Dolorum nihil quasi alias, perspiciatis voluptates, ipsa quas sunt pariatur odit corrupti doloribus est. Veniam dolore dolor enim officia est rerum quibusdam quis consectetur, ut nobis nulla tempora molestias pariatur laudantium quia esse.</p> 

        <p>Perspiciatis beatae sapiente commodi doloribus vel voluptatem culpa quo? Deserunt aliquid nesciunt dolorem expedita, quisquam ipsa eveniet nulla laboriosam quod quo? Iste, debitis ullam? Quae consequuntur dolore dolores fuga deleniti voluptas repellendus doloremque quas cupiditate, obcaecati, at architecto quo explicabo amet, unde repellat? Ad saepe non perspiciatis iure.</p>
    </section>

    <section class="blog">
       <?php foreach($articles as $article): ?>
			
			<article class="accueil">
				<div>
					<h3><?= htmlspecialchars($article['titre']) ?></h3>
					<p>Dans la catégorie : <span><?= htmlspecialchars($article['category_name']) ?></span></p>
				</div>
				<div>
					<p><?=$article['content100']?>...</p>
					<button><a href="index.php?page=article&id_article=<?= $article['id_article'] ?>">Voir plus</a></button>
				</div>
				
				<footer>
					<p>Rédigé par <strong><?=htmlspecialchars($article['first_name'])?> <?=htmlspecialchars($article['last_name'])?></strong> le <?= $article['newDate']?> </p>
				</footer>
			</article>
		
		<?php endforeach; ?>

    </section>
    
</main>
