<main>
	
	<article>
		
		<h1><?= htmlspecialchars($article['titre']) ?></h1>
		<img src="<?= htmlspecialchars($article['src']) ?>" alt="<?= htmlspecialchars($article['alt']) ?>">
		<p>Dans la catégorie <span><?= htmlspecialchars($article['category_name']) ?></span></p>
		<p><?= $article['content'] ?></p>
		<p>Rédigé par <strong><?=htmlspecialchars($article['first_name'])?> <?=htmlspecialchars($article['last_name'])?></strong> le <?= $article['newDate']?> </p>
	</article>
	
</main>