<main>
	
	<article>
		
		<h1><?= htmlspecialchars($article['titre']) ?></h1>
		<img src="<?= htmlspecialchars($article['src_img']) ?>" alt="<?= htmlspecialchars($article['alt_img']) ?>">
		<p>Dans la catégorie <span><?= htmlspecialchars($article['categoryName']) ?></span></p>
		<p><?= $article['content'] ?></p>
		<p>Rédigé par <strong><?=htmlspecialchars($article['first_name'])?> <?=htmlspecialchars($article['last_name'])?></strong> le <?= $article['newDate']?> </p>
	</article>
	
</main>