<main class="login">

	<form method="post" class="log-in">
		
		<h1>Connexion...</h1>
		<p>
			<label for='email'>Email</label>
			<input type="email" name="email" id="email">
		</p>
		<p><?= $this -> message1 ?></p>
		<p>
			<label for='pw'>Mot de passe</label>
			<input type="password" name="pw" id="pw">
		</p>
		<p><?= $this -> message2 ?></p>
		<button>Se connecter</button>
		
	</form>
	<li><a href="newUser">Créer un compte</a></li>
</main>
