<main>
    
    	<h1>Tableau de bord</h1>
    	
    <p>nombre plats en bdd : <?= $nb['nb'] ?> plats  </p> 

<nav class="dashboard">
    <a href="index.php?page=modifyHome">page d'accueil</a>
    <a href="index.php?page=modifyGame">jeu</a>
    <a href="index.php?page=modifyMerch">page merch</a>
    <a href="index.php?page=modifyAbout">page about</a>
    <a href="index.php?page=category">Gestions des catégories</a>
</nav>



</main>
