<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="description" content="Mon projet personnel : un site événement">
	<title>Projet Perso</title>
	<!--google fonts-->
	<link href="https://fonts.googleapis.com/css?family=Athiti:500|Merienda:400,700&display=swap" rel="stylesheet">
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Orbitron&display=swap" rel="stylesheet">
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Chakra+Petch&display=swap" rel="stylesheet">
	<!--font awesome-->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/fontawesome.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/brands.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/solid.min.css">
	<!--feuille css-->
	<link rel="stylesheet" href="assets/css/style.css">
</head>
<body>

	<header>
		<nav>
			<a href="home"><img src="assets/img/logo3.png" alt="logo_snake"></a>
				<a href="index.php">Home</a>
				<a href="index.php#about">About</a>
				<a href="jeu">Jeu</a>
				<a href="shop">Shop</a>
				<a href="cart"><i class="fas fa-shopping-bag"></i></a>
				<?php if(isset($_SESSION['user'])): ?>
					<a href="account"><i class="fas fa-user"></a>
					<p>Bonjour <?= $_SESSION['user'] ?></p>
					<a href="index.php?page=connexion&action=deco">Log out</a>
				<?php else: ?>
	           		<a href="connexion"><i class="fas fa-user"></i></a>
				<?php endif; ?>
			<div class="admin">
				<?php if(isset($_SESSION['admin'])): ?>
					<p>Bonjour <?= $_SESSION['admin'] ?></p>
					<a href="index.php?page=dashboard">Dashboard</a>
					<a href="index.php?page=admin&action=deco"><i class="fas fa-user-slash"></i></a>
				<?php endif; ?>
			</div>
		</nav>
		
	</header>
	
	<!-- code principal de la page -->
	<?php include $template ?>
	
	<button><a href="#"><i class="fas fa-angle-double-up"></i></a></button>
	
	<footer class="bottom">
		<div class="contact">
		</div>
		<button>Télécharger le PDF</button>
		<div class="networks">
		</div>
	</footer>
	<script type="text/javascript" src="assets/js/main.js"></script>

	</body>
</html>
	
	
	