<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="description" content="Mon projet personnel : un site événement">
	<title>Projet Perso</title>
	<!--google fonts-->
	<link href="https://fonts.googleapis.com/css?family=Athiti:500|Merienda:400,700&display=swap" rel="stylesheet">
	<!--font awesome-->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/fontawesome.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/brands.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/solid.min.css">
	<!--feuille css-->
	<link rel="stylesheet" href="assets/css/style.css">
</head>
<body>

	<header>
		<div class="logo">
			<img src="" alt="">
		</div>
		<nav>
			<div class="home">
				<a href="index.php">Home</a>
				<a href="#">Jeu</a>
				<a href="#">Merch</a>
				<a href="#">About</a>
				<a href="#">Connexion</a>
			</div>
			<div class="admin">
				<?php if(isset($_SESSION['admin'])): ?>
					<p>Bonjour <?= $_SESSION['admin'] ?></p>
					<a href="index.php?page=dashboard">Dashboard</a>
					<a href="index.php?page=admin&action=deco">Log out</a>
				<?php endif; ?>
			</div>
		</nav>
		
	</header>
	
	<!-- code principal de la page -->
	<?php include $template ?>
	
	<footer class="bottom">
		<div class="contact">
		</div>
		<button>Télécharger le PDF</button>
		<div class="networks">
		</div>
	</footer>
	</body>
</html>
	
	
	