
    <table>
        <tr>
            <th>Nom</th>
            <th>Prix</th>
            <th>Quantité</th>
        </tr>
        <?php foreach($_SESSION["shopping_cart"] as $cart): ?>
        <tr>
            <td><?= $cart['item_name'] ?></td>
            <td><?= $cart['item_price'] ?> €</td>
            <td><?= $cart['item_quantity'] ?></td>
            <td><button><a href="modifCart-<?= $cart['item_id'] ?>">suppr</a></button></td>
        </tr>
        <?php endforeach ?>
        <tr>
            <tfoot>
                <td>total</td>
            </tfoot>
        </tr>
    </table>
    