<main>
	
	<article>
		<h1><?= htmlspecialchars($product['product_name']) ?></h1>
		<img src="<?= htmlspecialchars($product['src_img']) ?>" alt="<?= htmlspecialchars($product['alt_img']) ?>">
		<p>Dans la catégorie <span><?= htmlspecialchars($product['categoryName']) ?></span></p>
		<p><?= $product['description'] ?></p>
		<p><?=htmlspecialchars($product['price'])?></p> 
	</article>
	
	<form>
		<input id="qte<?= $product['id_product'] ?>"type="text" name="quantity" value="1" />  
	    <input id="nom<?= $product['id_product'] ?>" type="hidden" name="hidden_name" value="<?= $product["product_name"]; ?>" />  
	    <input id="px<?= $product['id_product'] ?>" type="hidden" name="hidden_price" value="<?=$product["price"]; ?>" />  
	    <input data-id="<?= $product['id_product'] ?>"  type="submit" name="add_to_cart" class="btn" value="Add to Cart" />  
     </form>
	
	
</main>