<main>
	
	<article>
		<h1><?= htmlspecialchars($product['product_name']) ?></h1>
		<img src="<?= htmlspecialchars($product['src_img']) ?>" alt="<?= htmlspecialchars($product['alt_img']) ?>">
		<p>Dans la catégorie <span><?= htmlspecialchars($product['categoryName']) ?></span></p>
		<p><?= $product['description'] ?></p>
		<p><?=htmlspecialchars($product['price'])?></p> 
		<p><?= $product['newDate']?> </p>
	</article>
	
</main>