<main class="login">
	<form method="post">
		<p>
			<label for='login'><i class="fas fa-portrait"></i> Login</label>
			<input type="text" name="login" id="login">
		</p>
		<p><?= $this -> message1 ?></p>
		<p>
			<label for='pw'><i class="fas fa-lock"></i> Mot de passe</label>
			<input type="password" name="pw" id="pw">
		</p>
		<p><?= $this -> message2 ?></p>
		<button>LOGIN</button>
	</form>
</main>