<main>
    
    <h1>Tableau de bord</h1>
    	
    <nav class="log-in">
        <p><a href="index.php?page=gestionAccueil">Gestion accueil</a></p>
        <p><a href="index.php?page=gestionArticle">Gestion blog</a></p>
        <p><a href="index.php?page=gestionCategory">Gestions des catégories</a></p>
        <p><a href="index.php?page=gestionAuthor">Gestions des auteurs</a></p>
        <p><a href="index.php?page=gestionProduct">Gestion shop</a></p>
    </nav>

</main>
