<main>
    
    <h1>Tableau de bord</h1>
    	
    <nav class="dashboard">
        <p><a href="index.php?page=modifyHome">page d'accueil</a></p>
        <p><a href="index.php?page=modifyGame">jeu</a></p>
        <p><a href="index.php?page=gestionArticle">Gestion blog</a></p>
        <p><a href="index.php?page=modifyMerch">page merch</a></p>
        <p><a href="index.php?page=modifyAbout">page about</a></p>
        <p><a href="index.php?page=category">Gestions des catégories</a></p>
    </nav>

</main>
