<main>
    
    <h1>Tableau de bord</h1>
    	
    <nav class="dashboard">
        <p><a href="index.php?page=modifyHome">page d'accueil</a></p>
        <p><a href="index.php?page=gestionArticle">Gestion blog</a></p>
        <p><a href="index.php?page=gestionCategory">Gestions des catégories</a></p>
        <p><a href="index.php?page=gestionAuthor">Gestions des auteurs</a></p>
        <p><a href="index.php?page=gestionProduct">Gestion shop</a></p>
        <p><a href="index.php?page=modifyAbout">page about</a></p>
        <p><a href="index.php?page=modifyGame">jeu</a></p>
        
    </nav>

</main>
