 <section>
 <h2>Gestion des catégories</h2>
    
        <button><a href="index.php?page=addCategory">Ajouter une catégorie de plat</a></button>
    
    
        <table>
            
            <tr>
                <th>ID</th>
                <th>Catégorie</th>
                <th>Modifier</th>
                <th>Supprimer</th>
            </tr>
            <?php foreach($categories as $category): ?>
            <tr>
                <td><?= $category['id_category'] ?></td>
                <td><?= $category['category_name'] ?></td>
                <td><button><a href="index.php?page=modifyCategory&id=<?=$category['id_category']?>"><i class="fas fa-pen-nib"></i>modif</a></button></td>
                <td><button class="confirmButton" data-url="<?= "index.php?page=deleteCategory&id=".$category['id_category'] ?>"><a><i class="fas fa-trash-alt"></i>suppr</a></button></td>
            </tr>
            <?php endforeach; ?>
        </table>
    
    </section>


</main>
    <script src="js/main.js"></script>
