 <section>
 <h2>Gestion des plats</h2>
    
        <button><a href="index.php?page=createMeal">Ajouter un plat</a></button>
    
        <table>
            <tr>
                <th>ID</th>
                <th>Catégorie</th>
                <th>Titre</th>
                <th>Auteur</th>
                <th>Image src</th>
                <th>Image alt</th>
                <th>Modifier</th>
                <th>Supprimer</th>
            </tr>
            <?php foreach($articles as $article): ?>
            <tr>
                <td><?= $article['id_article'] ?></td>
                <td><?= $article['category_name'] ?></td>
                <td><?= $article['titre'] ?></td>
                <td><?= $article['first_name'], $article['last_name'] ?></td>
                <td><?= $article['src'] ?></td>
                <td><?= $article['alt'] ?></td>
                <td><button><a href="index.php?page=modifyArticle&id=<?=$article['id_article']?>"><i class="fas fa-pen-nib"></i></a></a></button></td>
                <td><button class="confirmButton" data-url="<?= "index.php?page=deleteMeal&id=".$meal['id'] ?>"><a><i class="fas fa-trash-alt"></i></a></button></td>
            </tr>
            <?php endforeach; ?>
        </table>
    
    </section>


</main>