<main>

 <section>
 <h2>Gestion de l'accueil</h2>
 
        <table class="gestion">
            <tr>
                <th>Name</th>
                <th>Content</th>
                <th>src</th>
                <th>alt</th>
                <th>Modifier</th>
                <th>Supprimer</th>
            </tr>
            <?php foreach($contents as $content): ?>
            <tr>
                <td><?= $content['name'] ?></td>
                <td><?= $content['content'] ?></td>
                <td><?= $content['src_img'] ?></td>
                <td><?= $content['alt_img'] ?></td>
                <td><button><a href="index.php?page=modifyHome&id=<?=$content['id']?>"><i class="fas fa-pen-nib"></i></a></button></td>
            </tr>
            <?php endforeach; ?>
        </table>
    
    </section>


</main>
    <script src="js/main.js"></script>

